project:
  type: "website"
  title: "Fall 2025 Courses"
  output-dir: _output
  render:
    - "./index.qmd"
    - "2025-logic/*"
    - "2025-aesthetics/*"

website:
  title: "Fall 2025"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card:
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: ./index.qmd
        text: "ğŸ  Lecture Notes and Slides"
      - section: "ğŸ—“ï¸ Logic"
        contents:
         - href: 2025-logic/weeks/week01/page.qmd
           text: Week 01
           contents:
             - href: 2025-logic/weeks/week01/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week02/page.qmd
           text: Week 02
           contents:
             - href: 2025-logic/weeks/week02/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week03/page.qmd
           text: Week 03
           contents:
             - href: 2025-logic/weeks/week03/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2025-aesthetics/weeks/week06/summary.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week04/page.qmd
           text: Week 04
           contents:
             - href: 2025-logic/weeks/week04/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2025-logic/weeks/week04/summary.qmd
               text: ğŸ’» Study Guide
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week05/page.qmd
           text: Week 05
           contents:
             - href: 2025-logic/weeks/week05/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
            #  - href: 2025-aesthetics/weeks/week06/summary.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week06/page.qmd
           text: Week 06
           contents:
             - href: 2025-logic/weeks/week06/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2025-logic/weeks/week06/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week07/page.qmd
           text: Week 07
           contents:
             - href: 2025-logic/weeks/week07/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2025-logic/weeks/week07/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week08-predicates/page.qmd
           text: Week 07
           contents:
             - href: 2025-logic/weeks/week08-predicates/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2025-logic/weeks/week08-predicates/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix


      - section: "ğŸ—“ï¸ Aesthetics"
        contents:
          #        - href: 2025-aesthetics/weeks/week01/page.qmd
          # text: Discussion 01
          # contents:
          #   - href: 2025-aesthetics/weeks/week02/page.qmd
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix

      - section: "ğŸ—“ï¸ Aesthetics"
        contents:
          #        - href: 2025-aesthetics/weeks/week01/page.qmd
          # text: Discussion 01
          # contents:
          #   - href: 2025-aesthetics/weeks/week02/page.qmd
          #     text: ğŸ‘¨â€ğŸ« Lecture Material
          #   - href: 2025-aesthetics/weeks/week02/summary.qmd
          #     text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week03/page.qmd
           text: Discussion 02
           contents:
             - href: 2025-aesthetics/weeks/week03/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week03/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week04/page.qmd
           text: Discussion 03
           contents:
             - href: 2025-aesthetics/weeks/week04/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week04/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week05/page.qmd
           text: Discussion 04
           contents:
             - href: 2025-aesthetics/weeks/week05/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week05/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week06/page.qmd
           text: Discussion 05
           contents:
             - href: 2025-aesthetics/weeks/week06/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week06/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week07/page.qmd
           text: Discussion 07
           contents:
             - href: 2025-aesthetics/weeks/week07/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week07/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week08/page.qmd
           text: Discussion 08
           contents:
             - href: 2025-aesthetics/weeks/week08/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week08/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week09/page.qmd
           text: Discussion 09
           contents:
             - href: 2025-aesthetics/weeks/week09/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week09/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix href: 2025-aesthetics/weeks/week08/page.qmd
         - href: 2025-aesthetics/weeks/week10/page.qmd
           text: Discussion 10
           contents:
             - href: 2025-aesthetics/weeks/week11/summary.qmd
               text: ğŸ’» Notes and Summarya
         - href: 2025-aesthetics/weeks/week12/page.qmd
           text: Discussion 12
           contents:
             - href: 2025-aesthetics/weeks/week12/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week12/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: 2025-aesthetics/weeks/week13/page.qmd
           text: Discussion 13 - Kant on the Critique of the Power of Judgment
           contents:
             - href: 2025-aesthetics/weeks/week13/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week13/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: 2025-aesthetics/weeks/week14/page.qmd
           text: Discussion 14 - David Hume - On Tragedy
           contents:
             - href: 2025-aesthetics/weeks/week14/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2025-aesthetics/weeks/week14/summary.qmd
               text: ğŸ’» Notes and Summary







  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2025, Montaque Reynolds"



bibliography: references/Un-Duplicates.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Dr. [Reynolds](#)
    author-meta: Dr. Monty Reynolds
    date-format: "MMM DD, YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)

    theme:
      light:
        - journal
        - css/custom.scss # I use this just to change the default colour
    css:
      - css/custom_style.css
      - css/syllabus.css
    toc: true

margin-header: |
 ![](/figures/logos/logo-x2.png)
