project:
  type: "website"
  title: "Fall 2025 Courses"
  output-dir: _output
  render:
    - "./index.qmd"
    - "./2025-aesthetics/*"

website:
  title: "Philosophy of Law, Spring 2026"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card:
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - section: "ğŸ—“ï¸ Aesthetics"
        contents:
         - href: ./2025-aesthetics/weeks/week03/page.qmd
           text: Discussion 02
           contents:
             - href: ./2025-aesthetics/weeks/week03/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week03/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: ./2025-aesthetics/weeks/week04/page.qmd
           text: Discussion 03
           contents:
             - href: ./2025-aesthetics/weeks/week04/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week04/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: ./2025-aesthetics/weeks/week05/page.qmd
           text: Discussion 04
           contents:
             - href: ./2025-aesthetics/weeks/week05/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week05/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: ./2025-aesthetics/weeks/week06/page.qmd
           text: Discussion 05
           contents:
             - href: ./2025-aesthetics/weeks/week06/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week06/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: ./2025-aesthetics/weeks/week07/page.qmd
           text: Discussion 07
           contents:
             - href: ./2025-aesthetics/weeks/week07/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week07/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: ./2025-aesthetics/weeks/week08/page.qmd
           text: Discussion 08
           contents:
             - href: ./2025-aesthetics/weeks/week08/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week08/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: ./2025-aesthetics/weeks/week09/page.qmd
           text: Discussion 09
           contents:
             - href: ./2025-aesthetics/weeks/week09/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week09/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix href: ./2025-aesthetics/weeks/week08/page.qmd
         - href: ./2025-aesthetics/weeks/week10/page.qmd
           text: Discussion 10
           contents:
             - href: ./2025-aesthetics/weeks/week11/summary.qmd
               text: ğŸ’» Notes and Summarya
         - href: ./2025-aesthetics/weeks/week12/page.qmd
           text: Discussion 12
           contents:
             - href: ./2025-aesthetics/weeks/week12/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week12/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week13/page.qmd
           text: Discussion 13 - Kant on the Critique of the Power of Judgment
           contents:
             - href: ./2025-aesthetics/weeks/week13/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week13/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week14/page.qmd
           text: Discussion 14 - David Hume - On Tragedy
           contents:
             - href: ./2025-aesthetics/weeks/week14/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week14/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week15/page.qmd
           text: Discussion 15 - Hegel - Art is Done
           contents:
             - href: ./2025-aesthetics/weeks/week15/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week15/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week16/page.qmd
           text: Discussion 15 - Heiddegger - The Origin of the Work of Art
           contents:
             - href: ./2025-aesthetics/weeks/week16/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week16/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week17/page.qmd
           text: Discussion 17 - Tavinor's - The Art of Video Games
           contents:
             - href: ./2025-aesthetics/weeks/week17/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week17/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week18/page.qmd
           text: Discussion 18 - Tavinor's - The Art of Video Games
           contents:
             - href: ./2025-aesthetics/weeks/week18/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week18/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week19/page.qmd
           text: Discussion 19 - Tavinor's - The Art of Video Games
           contents:
             - href: ./2025-aesthetics/weeks/week19/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week19/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week20/page.qmd
           text: Discussion 20 - Tavinor's - The Art of Video Games
           contents:
             - href: ./2025-aesthetics/weeks/week20/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week20/summary.qmd
               text: ğŸ’» Notes and Summary
         - href: ./2025-aesthetics/weeks/week22-review/page.qmd
           text: Discussion 22 - Final Review
           contents:
             - href: ./2025-aesthetics/weeks/week22-review/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: ./2025-aesthetics/weeks/week22-review/summary.qmd
               text: ğŸ’» Notes and Summary


  navbar:
    background: primary

  page-footer:
    background: light
    left: "Copyright 2025, Montaque Reynolds"

bibliography: /home/mreynolds/Sync/My-Library.bib
csl: references/chicago-author-date.csl

format:
  html:
    author: Dr. [Reynolds](#)
    author-meta: Dr. Monty Reynolds
    date-format: "MMM DD, YYYY"
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)
    theme:
      light:
        - journal
        - css/custom.scss
    css:
      - css/custom_style.css
      - css/syllabus.css
    toc: true

margin-header: |
  ![](/figures/logos/logo-x2.png)
