project:
  type: "website"
  title: "Introduction to Logic, Spring 2026"
  output-dir: _output
  render:
    - "./index.qmd"
    - "./2026_logic/*"

website:
  title: "Logic, Fall 2025"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card:
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - section: "ğŸ—“ï¸ Logic"
        contents:
         - href: 2026_logic/weeks/week01/page.qmd
           text: Week 01
           contents:
             - href: 2026_logic/weeks/week01/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week02/page.qmd
           text: Week 02
           contents:
             - href: 2026_logic/weeks/week02/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week03/page.qmd
           text: Week 03
           contents:
             - href: 2026_logic/weeks/week03/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2026_aesthetics/weeks/week06/summary.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week04/page.qmd
           text: Week 04
           contents:
             - href: 2026_logic/weeks/week04/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2026_logic/weeks/week04/summary.qmd
               text: ğŸ’» Study Guide
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week05/page.qmd
           text: Week 05
           contents:
             - href: 2026_logic/weeks/week05/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
            #  - href: 2026_aesthetics/weeks/week06/summary.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week06/page.qmd
           text: Week 06
           contents:
             - href: 2026_logic/weeks/week06/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2026_logic/weeks/week06/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week07/page.qmd
           text: Week 07
           contents:
             - href: 2026_logic/weeks/week07/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2026_logic/weeks/week07/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week08-predicates/page.qmd
           text: Week 08
           contents:
             - href: 2026_logic/weeks/week08-predicates/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2026_logic/weeks/week08-predicates/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_logic/weeks/week16_final-review/page.qmd
           text: Final Review
           contents:
             - href: 2026_logic/weeks/week16_final-review/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material/Propositional Logic Semantics
             - href: 2026_logic/weeks/week16_final-review/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix

  navbar:
    background: primary

  page-footer:
    background: light
    left: "Copyright 2025, Montaque Reynolds"

bibliography: ./Un-Duplicates.bib
csl: references/chicago-author-date.csl

format:
  html:
    author: Dr. [Reynolds](#)
    author-meta: Dr. Monty Reynolds
    date-format: "MMM DD, YYYY"
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)
    theme:
      light:
        - journal
        - css/custom.scss
    css:
      - css/custom_style.css
      - css/syllabus.css
    toc: true
    html:
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
          window.MathJax = {
            loader: { load: ['[tex]/bussproofs'] },
            tex: { packages: {'[+]': ['bussproofs']} }
          };
        </script>
    margin-header: |
      ![](/figures/logos/logo-x2.png)
