project:
  type: "website"
  title: "Fall 2025 Courses"
  output-dir: _output
  render:
    - "./index.qmd"
    - "2025-logic/*"
    - "2025-aesthetics"

website:
  title: "Fall 2025"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card:
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: ./index.qmd
        text: "ğŸ  Home"
      - section: "ğŸ—“ï¸ Weeks"
        contents:
         - href: 2025-logic/weeks/week01/page.qmd
           text: Week 01
           contents:
             - href: 2025-logic/weeks/week01/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-logic/weeks/week02/page.qmd
           text: Week 02
           contents:
             - href: 2025-logic/weeks/week02/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2025-aesthetics/weeks/week02/page.qmd
           text: Week 02
           contents:
             - href: 2025-aesthetics/weeks/week02/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2023/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix

  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2025, Stetson University"



bibliography: references/references.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Dr. [Reynolds](#)
    author-meta: Dr. Monty Reynolds
    date-format: "MMM DD, YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)

    theme:
      light:
        - journal
        - css/custom.scss # I use this just to change the default colour
    css:
      - css/custom_style.css
      - css/syllabus.css
    toc: true

margin-header: |
 ![](/figures/logos/logo-x2.png)
